version: '3'

services:
  backend:
    image: your-docker-image:latest
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=us-east-1
      - ENV_NAME=production
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

volumes:
  dynamodb_data:
